### ISSUE TITLE
KODI audio passthrough in Flatpak

### ISSUE THREAD

**Issue by ENKI101** [gamer-os/gamer-os#121]
How to enable? Flatpak is new to me.
KODI_AE_SINK=ALSA, or with pasuspender -- env. But where do I have to set this?

**Comment by ChojinDSL** [comment]
I got it working by setting the audio to 2.0 speakers in steam's audio settings.

This makes sense since even the official KODI docs state that if you use pulseaudio, you need to set your profile to 2.0 speakers, in order for passthru to work. 

Whats annoying is that if you want surround sound from your games, you always have to go back into steam and change it back to 5.1. 

I guess a compromise would be to set kodi to 5.1 pulseaudio. But then kodi does the mixing. 
This could be entirely subjective, but I get the feeling that proper, pure passthru sounds better on my amp than pulseaudio 5.1.

**Comment by ENKI101** [comment]
My friend, thank you for reply. I tried, but in Kodi, the options for audio passthrough still don't appear, after setting in BigPicture to Digital Stereo 2.0 HDMI.

**Comment by ChojinDSL** [comment]
Did you also enable "Expert" in the system settings in kodi? You might need to restart steam when you change the audio settings. I usually do that via steam-buddy, it's faster than a full reboot.

**Comment by ENKI101** [comment]
Yes, I set to Expert mode.
Thank you for the hint to restart Steam via steam-buddy.
I restarted SteamOS, but nothing changed. Still no passthrough option in Kodi.
Do you also use HDMI/Displayport?

**Comment by ChojinDSL** [comment]
Yeah, probably that's not yet supported by Pulseaudio. 
The Kodi wiki mentions TrueHD and DTS-MA but if I had to guess I would say it probably also applies to Atmos and DTS-X considering how new those are.

> Note: PulseAudio does not currently allow TrueHD or DTS-MA passthrough, this is a PulseAudio limitation and not a limitation of the Kodi implementation, in order to get 7.1 audio Multichannel Mode must be used
