### ISSUE TITLE
Help with resolution and refresh rate

### ISSUE THREAD

**Issue by RafaelRestolho** [gamer-os/gamer-os#125]
I use my TV connected to my notebook to access GamerOS, however, the resolution is weird, I wonder how do I change the refresh rate etc

**Comment by alkazar** [comment]
You can customize the resolution and refresh rate by following the instructions here:
https://github.com/gamer-os/steamos-compositor-plus#configuration

**Comment by peterge1998** [comment]
After installing ChimeraOS and testing this, I found this is not working for me. I use the steam deck ui, and in the decks right hardware menuits still showing the frame rate cap for 15 | 30 | 60 | unlimited, after changing GOODRATES to "120.0" in ~/.config/steamos-compositor-plus.
I had a [similar problem on holoiso](https://github.com/theVakhovskeIsTaken/holoiso/issues/360) before, but I just came to Chimera because it supports auto updates :)

**Comment by pastaq** [comment]
This issue has been closed for 2 and a half years. Your issue is entirely different, and that config file is for BPM not GamepadUI. Please open a new issue to discuss your issue.
