### ISSUE TITLE
Best practice for installing packages via pacman?

### ISSUE THREAD

**Issue by m-kloeckner** [gamer-os/gamer-os#138]
I am currently using an Ubuntu based linux box for Steam gaming and GPU-accelerated calculations (Tensorflow/CUDA). However, I have multiple issues while gaming which gamer-os is solving! I therefore consider switching. However, I will need to install docker and some other tools alongside the standard gamer-os image.

Question: Is there a best practice in doing so?

I know that I can run frzr-unlock and then install packages. I already did that for a test - it works well. But all of this will be gone once a new upgrade is being pushed, correct?

Thank you for your awesome work on gamer-os! 
Martin

**Comment by alkazar** [comment]
I think you have two options:
1) Do not use GamerOS. Instead install Arch Linux and install the various GamerOS packages from the AUR plus any additional packages you wish.
2) If you still really need/want the atomic update system, you can fork this repo, add your additional packages to the manifest file, build your own image, and point the installer at your repo instead of this one.
