### ISSUE TITLE
Create Arch Linux install script for Gamer OS

### ISSUE THREAD

**Issue by leocodeninja** [gamer-os/gamer-os#177]
Can you make an Arch install script for a Gamer OS install with a normal Arch install so I could also use it for non-game stuff occasionally?

**Comment by Thijzer** [comment]
I already did an effort,
 - main script :  https://github.com/Thijzer/archinstaller/blob/main/build.sh  
 - repo : https://github.com/Thijzer/archinstaller

This repo is still a in development.
It doesn't include the frzr or btrs parts, just regular EXT4
I was able to build a provision in image mode but the script mode is untested

**Comment by alkazar** [comment]
I found this kind of funny since this is how GamerOS started out. There is still an old branch where you can obtain the original installation script, but I have no idea if it still works: https://github.com/gamer-os/gamer-os/tree/arch_installer

I have a few other recommendations though:
1) you can fork the GamerOS repo and edit the manifest file to add any additional packages you like, then enable Github Actions on your fork to have Github build the image for you. Finally, install GamerOS, then from the command line run `sudo frzr-deploy leocodeninja/gamer-os:unstable` to install your fork. Any time you make changes Github will automatically build a new image and your system will update to it.
2) Install GamerOS, then run `sudo frzr-unlock` and `sudo pacman -Syy`, finally run `systemctl disable frzr-autoupdate` to prevent the system from reverting back to the locked down version of GamerOS in a future update. Now you have a full Arch Linux system, but you will miss out on future GamerOS updates.

**Comment by alkazar** [comment]
I am not going to actually create a script to do this and maintain it though, sorry.
