### ISSUE TITLE
trim is not enabled on SSDs

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#22]

**Comment by sharkwouter** [comment]
I solved this for VaporOS by packaging the scripts used for trim in Ubuntu. You can find the package source here: https://github.com/sharkwouter/vaporos-brewmaster/blob/master/sources/vaporos-trim-support2_2.1.tar.gz

It is GPL licensed, but since config files are just plain text files that shouldn't be an issue.

**Comment by sharkwouter** [comment]
This is addressed by pull request #31

**Comment by alkazar** [comment]
Nice job @sharkwouter, thanks!
