### ISSUE TITLE
Debian / Ubuntu script

### ISSUE THREAD

**Issue by brandleesee** [gamer-os/gamer-os#23]
For those that are more into Debian and Ubuntu....
Would you provide a script that caters for those, please?
Thank you.

**Comment by alkazar** [comment]
You probably want:
https://github.com/ShadowApex/steamos-ubuntu

However, I think you may be misunderstanding what gamerOS is. gamerOS is
not Arch. It is a read only snapshot of a preconfigured Arch install,
updated every now and then. You cannot use pacman or the AUR. You dont need
to know anything about Arch to run gamerOS.

Interestingly, gamerOS is flexible enough that the distro used to build the
read only snapshots is actually irrelevant and can be changed at any time.
I chose Arch because it gives the easiest access to the latest packages.

gamerOS is actually somewhat similar to docker. You create OS images and
run them. The big difference is that gamerOS does not run containers, it is
like running a docker image as the host OS itself.

**Comment by brandleesee** [comment]
I see so as such Arch is only needed as it is the easiest way to install a stand alone image. Once on usb the is no more Arch (never has been) but gamerOS. Meanwhile, is the script configured to be persistent on live media? This to save game progress...

**Comment by alkazar** [comment]
Yes, there is persistence. It works very well running off a usb, other than
the obvious problem of slow disk i/o. I actually test using a usb stick and
it even works across different computers with different graphics cards and
drivers.

**Comment by brandleesee** [comment]
Noted. Am closing this issue because this is, after all, a stand-alone operating system. Arch is only needed to build it. Thank you.
