### ISSUE TITLE
Updates should happen automatically

### ISSUE THREAD

**Issue by sharkwouter** [gamer-os/gamer-os#34]
The 1.0 release should probably contain an automatic updater. Currently gamerOS is lacking this. It should give feedback to the user about its progress as well. Plymouth would probably be the best way to do this.

Plymouth and UEFI support will need to be finished before that, though. After automatic updates have been enabled, no significant changes can be made to frzr anymore or it will break the feature.

**Comment by alkazar** [comment]
Updates do happen automatically. Is it not working for you? There isn't a
need to show progress since you can continue to use your system while the
update happens in the background.

Might be nice if we could have some way to notify the user once an update
is done so they could decide to restart to complete the process.

frzr can and is updated, you do have to be a little careful with backwards
compatibility. Changes you make won't take effect until the next release,
since an updated frzr won't run until it is actually installed.

**Comment by sharkwouter** [comment]
I didn't realize that. That explains the frzr-autoupdater error I saw when shutting down the system. I'll look into it some more to see what's wrong with it.

I suspect updating the system will slow the system down to a crawl, though, that's why I'd prefer doing it when the users wants to and showing the user what the system is doing. That would be a good one to test.

Informing user a reboot is required is surprisingly easy actually. Create a file called ``/var/run/reboot-required`` and run ``steam steam://refreshinbox`` as the user. We may want to just set a timer which goes off every couple of minutes to run the refreshinbox command, since Steam will otherwise never check for notifications.
