### ISSUE TITLE
Karaoke game for GamerOS needed

### ISSUE THREAD

**Issue by Tiger862000** [gamer-os/gamer-os#55]
Hi,
first, you guys are amazing for what you created! With the integration of the Retrogame-Emulators. Thank you for that in specific as Steam will probably newer release their integration.

However I do miss the support for an open source karaoke game. On steam there is none, or non that is comparable to what I'm searching for. To my knowledge there are two rather oldies but goldies: 
- Ultrastar Deluxe: An open Singstar clone <https://usdx.eu>
- Performous: An open Rockband clone with integrated Singstar functionality. Apparently it builds on sources from Ultrastar <http://performous.org>

What speaks for them:
- You can create your own karaoke songs or get them from known sources. Means you can enjoy jodeling your favourite songs wherever and whenever you want.
- They are stable, just work and are well tested.
- Supported on many platforms (Windows, Linux [Ubuntu, Arch, Fedora,...], Mac)
- Their sources are all online on github or sourceforge...

Now the problem being, neither of those games is available as flatpak nor as snap or Appimage.
I do not think anyone will port them to flathub.

Would be really great if you can make this one exception for this game and let it install from e.g. AUR, please?

Regards, Tiger

**Comment by alkazar** [comment]
Hi, thanks for your suggestion.

Unfortunately, the nature of GamerOS means that in order to include these games we would have to pre-install them. Including a specific game violates the idea of keeping GamerOS minimal.

My suggestion would be to try creating a flatpak package yourself and post it to flathub. Or encourage the original developers to make flatpak packages.

Sorry.
