### ISSUE TITLE
NTP support is still missing

### ISSUE THREAD

**Issue by sharkwouter** [gamer-os/gamer-os#62]
I can't work on this right now, so I'm creating this issue for future reference. My system shows the wrong time and does not correct it. This is not a mature problem, but it is a bit annoying.

SteamOS uses chrony as NTP daemon. The configuration for Chrony is not that straightforward, but it should work better on systems which aren't always online. There is a page about it on the Arch wiki: https://wiki.archlinux.org/index.php/Chrony

**Comment by tommy4st** [comment]
As GamerOS uses Systemd it's probably best to use it's implementation instead of Chrony: [systemd-timesyncd](https://wiki.archlinux.org/index.php/Systemd-timesyncd)

I just checked and the default values for NTP servers in Arch should be working.

I can prepare a PR for this (it's fairly simple as it just enables the systemd-timesyncd service)

**Comment by sharkwouter** [comment]
Oh, that could work as well. The default Chrony configuration isn't really usable, so this might be a good solution

**Comment by alkazar** [comment]
Now added in GamerOS 15.
