### ISSUE TITLE
use github actions to build system images

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#63]

**Comment by tommy4st** [comment]
I tried to setup a build in Docker, but this failed because of the loop mount. When using ostree, you probably don't need to loop mount anymore and it will possibly work. I tried to set up a Docker container based on the [Arch image](https://hub.docker.com/_/archlinux), where all dependencies are installed. (It's a little bit difficult because makepkg won't run as root)

```sh
export BASE="$PWD"
pacman -Suy --noconfirm
pacman -S --needed --noconfirm base-devel git btrfs-progs arch-install-scripts
cd /tmp
useradd -m someone
echo "someone ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
sudo -u someone git clone https://aur.archlinux.org/pikaur.git
cd pikaur
sudo -u someone makepkg -fsri --noconfirm
cd $BASE
```

**Comment by alkazar** [comment]
I think it should be possible to do this by doing the mount on the host system and doing the rest of the build in the docker container.
