### ISSUE TITLE
No audio after install

### ISSUE THREAD

**Issue by xpdos** [gamer-os/gamer-os#69]

**Comment by xpdos** [comment]
I just installed the new GamerOS after finally leaving SteamOS. I have an alienware Alpha r1 which has the 860m Nvidia chip. Everything appears to work except no sound through HDMI. I have toggled through the audio interface setting but no sound is outputted. I realize that this OS is more locked down than steamOS was, so how can I troubleshoot?

**Comment by tommy4st** [comment]
"Locked down" with GamerOS is quite relative. You can unlock you whole system by running `sudo frzr-unlock` in a terminal session. After a system update your changes will be overwritten, so it's a good idea to report back here, if you find an actual problem or solution.

**Comment by alkazar** [comment]
Sorry to hear things aren't working for you. I have found in the past that the Steam client UI for audio output switching can be finicky. I've had to select the output multiple times before it would work.

GamerOS is essentially Arch Linux, so looking at `journalctl` logs might be a start to see if there are any errors reported.

You can also try opening a tty and using `pacmd` to set the output manually.
Use `pacmd list-sinks` to show the available outputs.
Then use `pacmd set-default-sink <index>` to set the output.

I wonder if the issue is this one mentioned in the Arch wiki: https://wiki.archlinux.org/index.php/PulseAudio/Examples#Manually_configuring_PulseAudio_to_detect_the_Nvidia_HDMI

It seems pulseaudio cannot use HDMI audio if it is not the first device. Not sure how old that information is though. Note that GamerOS does not have the `aplay` command.

**Comment by xpdos** [comment]
Thanks for the replies, I ultimately switched to manjaro and was able to get it working with some extra packages.

**Comment by eyecreate** [comment]
I have this same hardware and issue. I tried setting with pacmd command, but nothing changed. I eventually unlocked the filesystem and installed pavucontrol, which allowed me to set HDMI as output and not the default of optical audio. I then had audio and it persisted on reboots(until a future update I assume). I am willing to test things to help make this smoother for devices like this.

**Comment by thesleort** [comment]
This is a problem for on my Alienware "Steam machine" as well. Installed it yesterday and everything works except audio through HDMI
